server:
  port: 8082
spring:
  application:
    name: greeting-api

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true
